Ct 177/add precommit hooks
dbt-labs/dbt-snowflake pull request #107
Opened 2022-03-13 22:58 UTC by VersusFacit

partially addresses #99 

### Description

Adds precommit hooks and tooling (e.g. a handy makefile) for this repo. 

Why these changes?
- suppressing duplicate module name errors is the best path forward
  1. mypy's import checker lacks nuance -- it doesn't allow for overrides which this project necessarily employs
  2. we can't change the directory paths easily -- I looked in this. There's too much coupling between the directory structure of this project and tooling in core
- suppressing attribute defined and missing type hint errors is the best path forward (this type information should live with upstream modules, namely `dbt` if we wanted static analysis in this repository)
  1. the mypy custom stub file model puts the onus _on_ to keep up to date with foreign modules which is work that isn't our responsibility
  2. a similar problem (by way of typed.py) affects imported libraries

### Checklist

- [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [X] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [X] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-snowflake next" section.

2022-03-13 22:59 UTC, VersusFacit commented on .pre-commit-config.yaml
> +    args: [--show-error-codes, --ignore-missing-imports]
Added the `--ignore-missing-imports` flag here to reduce in-code clutter. My argument is that all these errors tell you is that the upstream project lacks static type information, which isn't that powerful of knowledge.

2022-03-13 22:59 UTC, VersusFacit commented on dbt/adapters/snowflake/connections.py
> +from dbt.adapters.base import Credentials  # type: ignore
attr-defined errors are masked by this `# type: ignore` declaration

2022-03-15 13:42 UTC, gshank requested changes

2022-03-15 13:42 UTC, gshank commented on .flake8
> +max-line-length = 99
In dbt-core we removed the max-line-length and added E501 to the ignore, because of test contents. Black will format the code correctly to 99.

2022-03-23 10:37 UTC, jtcohen6 approved these changes

2022-03-29 06:51 UTC, VersusFacit commented on .pre-commit-config.yaml
> +    additional_dependencies: ['click==8.0.4']
Per https://github.com/psf/black/issues/2964#issuecomment-1080974737

2022-03-29 13:28 UTC, gshank approved these changes

2022-03-29 20:02 UTC, merged