Add conditional logic for kinds in changie.yaml
dbt-labs/dbt-snowflake pull request #227
Opened 2022-08-09 15:15 UTC by McKnight-42

### Description

### Checklist

- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

2022-08-09 20:19 UTC, emmyoop requested changes
Missed a kind.

2022-08-09 20:19 UTC, emmyoop commented on .changie.yaml
>  - label: Security
Also add it for this kind please.

2022-08-09 20:24 UTC, McKnight-42 commented on .changie.yaml
>  - label: Security
oh odd, fixed!

2022-08-25 18:59 UTC, emmyoop approved these changes

2022-08-25 19:22 UTC, merged