mirror issues to ADAP jira project
dbt-labs/dbt-snowflake pull request #460
Opened 2023-02-09 18:29 UTC by nathaniel-may

I'm attempting to mirror all the adapter issues into the new ADAP jira project. I found this new more generalized action and I think this is how you would call it.

If this gets approved I'll wait to merge all the automation changes all at once.

2023-02-13 17:53 UTC, emmyoop requested changes
Permissions needs to be set but otherwise looks good.

I've added an [issue](https://github.com/dbt-labs/dbt-core/issues/6955) in core to update the workflows there and clean up the extra repository.

2023-02-13 17:53 UTC, emmyoop commented on .github/workflows/jira-transition.yml
I'm not sure how the adapters are configured.  I believe @leahwicz configured `dbt-core` to have no permission so we have to explicitly define permissions (even read) in all workflows.  If the adapter repos are not also set up this way, they should be.  Workflows inherit permissions so even though the workflow you call has a read permission set, if this one doesn't it won't be able to read.

tldr - you should define the permission in each workflow

2023-02-14 20:18 UTC, nathaniel-may commented on .github/workflows/jira-transition.yml
makes sense. I copied the permission that core uses for the equivalent action.

2023-02-14 20:24 UTC, nssalian approved these changes

2023-02-27 17:24 UTC, merged