update used gh actions ahead of set-output, node12 deprecation
dbt-labs/dbt-snowflake pull request #580
Opened 2023-04-26 19:08 UTC by davidbloss

resolves #577 ADAP-485

### Description

Update versions of used Github Actions ahead of:

[node12 deprecation](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) (Summer 2023)
[set-output deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) fully disabled on 31st May 2023)

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

2023-04-26 19:16 UTC, emmyoop requested changes
This looks good.

We do need to update `bot-changelog.yml` as well but it's actually on me to make an update to the action we reference there to remove the deprecations.  This will be true of all the core + adapter repos.  I'll get that update done in the next few days and circle back to you.

2023-04-26 19:16 UTC, emmyoop commented on .changes/unreleased/Under the Hood-20230426-140930.yaml
> +  Issue: "577"
You can delete this and then add the `Skip Changelog` label to the PR. Since these changes have 0 effect on end users, we don't need a changelog.

2023-05-04 16:55 UTC, emmyoop approved these changes
Looks good.  I'll submit a separate PR for the changie_bot workflow.

2023-05-05 10:57 UTC, VersusFacit approved these changes

2023-05-05 19:00 UTC, merged