Add docker release to the full release process for final releases
dbt-labs/dbt-snowflake pull request #963
Opened 2024-04-03 03:27 UTC by mikealfare

### Problem

Publishing a Docker release is currently a manual process which can be forgotten.

### Solution

Add the Docker release to the release pipeline.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

2024-04-11 18:34 UTC, emmyoop requested changes

2024-04-11 18:44 UTC, mikealfare commented on .github/workflows/release.yml
> +  is-docker-release:
We weren't in the past, but otherwise I don't have a good reason. I'll remove this as it makes the workflow much more straight forward.

2024-04-11 18:46 UTC, mikealfare commented on .github/workflows/release.yml
> +      package: "dbt-snowflake"
Honestly, I would like to remove this entirely since the image now lives in the repo.

2024-04-12 05:08 UTC, mikealfare commented on .github/workflows/release.yml
> +    uses: dbt-labs/dbt-release/.github/workflows/release-docker.yml@er/update-local-run-docker
point this back to main

2024-04-12 16:41 UTC, mikealfare commented
This successfully published Docker [here](https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake/203116932?tag=1.8.0b2).

2024-04-12 16:46 UTC, emmyoop approved these changes

2024-04-12 21:16 UTC, mikealfare commented
Still publishes successfully: https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake/203198363?tag=1.8.0b2

2024-04-13 02:06 UTC, mikealfare commented on .github/workflows/release.yml
> +    uses: dbt-labs/dbt-release/.github/workflows/release-docker.yml@docker-release
Point this back to main

2024-04-15 21:34 UTC, merged